# Fail2Ban configuration file
#
# Author: xxxxxliil
# 
# Because of the rich rule commands and rich rules can use set as a source or target, requires firewalld 0.4.0+
# This action uses firewalld rich-rules and sets, which is faster than firewallcmd-rich-rules when dealing with a
# large number of IPs, and its multi-port behavior is similar to nftables-multiport.
#

[INCLUDES]

before = firewallcmd-common.conf

[Definition]

# TODO: Most firewalld objects require `--reload` to be created
# see https://github.com/firewalld/firewalld/issues/1400#issuecomment-2413975192
actionstart = <fwcmd_add_set>
              firewall-cmd --reload
              ports="<port>"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule "%(fwcmd_rich_rule)s"; done

actionstop = <fwcmd_delete_set>
             firewall-cmd --reload
             ports="<port>"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --remove-rich-rule "%(fwcmd_rich_rule)s"; done

# TODO: there doesn't seem to be an explicit way to invoke the ipset flush function using firewall-cmd
actionflush = <fwcmd_delete_set>
              <fwcmd_add_set>
              firewall-cmd --reload

actioncheck =

actionban = firewall-cmd --ipset <set_name> --add-entry <ip>
	   
actionunban = firewall-cmd --ipset <set_name> --remove-entry <ip>



fwcmd_add_set = firewall-cmd --permanent --new-ipset <set_name> --type hash:ip --family <set_family>

fwcmd_delete_set = firewall-cmd --permanent --delete-ipset <set_name>

fwcmd_rich_rule = rule family='<family>' source ipset=<set_name> port port='$p' protocol='<protocol>' %(rich-suffix)s

rich-suffix = <rich-blocktype>

set_name = f2b-<family>-<name>

# firewalld uses `inet{,6}` in sets and `ipv{4,6}` in rich rules, which is a bit cumbersome.
[Init]
set_family = inet

[Init?family=inet6]
set_family = inet6
